version: '3.7'
services:
  server:
    build: .
    depends_on:
      - mongodb
    environment:
      HOST: server
      PORT: 3030
      MONGODB_URL: mongodb://mongodb:27017/app
    ports:
      - target: 3030
        published: 3030
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: .
        target: /home/node/express-template
  mongodb:
    image: mongo:4.2.3
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
      - type: bind
        source: ./data/configdb
        target: /data/configdb
